# Generated by Django 6.0.5 on 2026-06-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="local_language_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
