# Generated by Django 6.0.5 on 2026-09-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "profiles",
            "0003_profile_city_profile_country_profile_date_of_birth_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="display_name_2",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="display_name_3",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
