# Generated by Django 6.0.5 on 2026-08-07 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profiles", "0002_profile_local_language_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("linkedin", "LinkedIn"),
                            ("portfolio", "Portfolio"),
                            ("website", "Website"),
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("youtube", "YouTube"),
                            ("steam", "Steam"),
                            ("discord", "Discord"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "platform_name",
                    models.CharField(
                        blank=True,
                        help_text="Only used when Platform is 'Other'.",
                        max_length=100,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=100)),
                ("url", models.URLField()),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "platform"],
            },
        ),
    ]
