# Generated by Django 6.0.5 on 2026-06-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visibility", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visibilityrule",
            name="field_name",
            field=models.CharField(
                choices=[
                    ("local_language_name", "Name (Local Language)"),
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("job_title", "Job Title"),
                    ("company", "Company"),
                    ("bio", "Bio"),
                ],
                max_length=50,
            ),
        ),
    ]
