# Generated by Django 6.0.5 on 2026-07-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visibility", "0002_alter_visibilityrule_field_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visibilityrule",
            name="visible_to",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("professional", "Professional"),
                    ("personal", "Personal"),
                    ("general", "General"),
                ],
                max_length=20,
            ),
        ),
    ]
