# Generated by Django 6.0.5 on 2026-07-21 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visibility", "0003_alter_visibilityrule_visible_to"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="visibilityrule",
            constraint=models.UniqueConstraint(
                fields=("owner", "field_name", "visible_to"),
                name="unique_visibility_rule",
            ),
        ),
    ]
