# Generated by Django 6.0.5 on 2026-08-07 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0001_initial"),
        ("visibility", "0005_alter_visibilityrule_visible_to"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="visibilityrule",
            name="field_name",
            field=models.CharField(
                choices=[
                    ("profile_picture", "Profile Picture"),
                    ("display_name", "Display Name"),
                    ("local_language_name", "Local Language Name"),
                    ("date_of_birth", "Date of Birth"),
                    ("nationality", "Nationality"),
                    ("languages_spoken", "Languages Spoken"),
                    ("country", "Country"),
                    ("city", "City"),
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("website", "Website"),
                    ("job_title", "Job Title"),
                    ("company", "Company"),
                    ("industry", "Industry"),
                    ("skills", "Skills"),
                    ("years_experience", "Years of Experience"),
                    ("bio", "Bio"),
                    ("interests", "Interests"),
                    ("hobbies", "Hobbies"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="LinkVisibilityRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visible_to",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("personal", "Personal"),
                            ("professional", "Professional"),
                            ("general", "General"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visibility_rules",
                        to="links.profilelink",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "link", "visible_to"),
                        name="unique_link_visibility_rule",
                    )
                ],
            },
        ),
    ]
