# Generated by Django 6.0.5 on 2026-09-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visibility", "0006_alter_visibilityrule_field_name_linkvisibilityrule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visibilityrule",
            name="field_name",
            field=models.CharField(
                choices=[
                    ("profile_picture", "Profile Picture"),
                    ("display_name", "Display Name"),
                    ("display_name_2", "Display Name 2"),
                    ("display_name_3", "Display Name 3"),
                    ("local_language_name", "Local Language Name"),
                    ("date_of_birth", "Date of Birth"),
                    ("nationality", "Nationality"),
                    ("languages_spoken", "Languages Spoken"),
                    ("country", "Country"),
                    ("city", "City"),
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("website", "Website"),
                    ("job_title", "Job Title"),
                    ("company", "Company"),
                    ("industry", "Industry"),
                    ("skills", "Skills"),
                    ("years_experience", "Years of Experience"),
                    ("bio", "Bio"),
                    ("interests", "Interests"),
                    ("hobbies", "Hobbies"),
                ],
                max_length=50,
            ),
        ),
    ]
